language: rust
rust: stable
os: linux
cache: cargo

install:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  # lint
  - cargo fmt --all -- --check
  - cargo clippy --all

  # build
  - cargo build --release

  # test
  - cargo test --all --release

  # doc build
  - cargo doc --no-deps

branches:
  only:
    - develop
